### ISSUE TITLE
开着魔法不能登录

### ISSUE THREAD

**Issue by KwdeTfpv** [gakkiyomi/fishpi-pyclient#81]
![image](https://github.com/gakkiyomi/fishpi-pyclient/assets/91249019/71029cfe-048e-485d-a6de-cc06a302c9b1)

**Comment by gakkiyomi** [comment]
截全一点 是全局代理吗 登录不上基本上就是fishpi.cn访问不了

**Comment by gakkiyomi** [comment]
> > 截全一点 是全局代理吗 登录不上基本上就是fishpi.cn访问不了
> 
> 不是全局，fishpi.cn是能访问的，但是登录好像是要做处理，requests时要不用代理

我的代理没问题，那你就当我的小白鼠吧 改完了先给你测测
